openapi: "3.0.0"
info:
  title: Simple Ticketing
  version: "0.1"
$ref: './components.yaml'
paths:
  /login:
    $ref: './paths/post_login.yaml'

  /tickets:
    $ref: './paths/tickets.yaml'

  /tickets/{id}:
    $ref: './paths/tickets_id.yaml'

  /tickets/{id}/messages:
    $ref: './paths/put_tickets_messages.yaml'